yamcs/yamcs

yamcs-core/bin/setlibrarypath.sh, yamcs-core/src/main/java/org/yamcs/ParameterValue.java, yamcs-web/src/main/java/org/yamcs/web/rest/AbstractRestRequestHandler.java, yamcs-web/src/main/java/org/yamcs/web/rest/MdbRequestHandler.java, yamcs-xtce/src/main/java/org/yamcs/xtce/NamedDescriptionIndex.java, yamcs-xtce/src/main/java/org/yamcs/xtce/xml/XtceAliasSet.java
Since the mininclusive/maxinclusive are optional primitives, we can just not fill them in. Clients should use the has-functions, or use wrappers.
=> Fixes "Infinite" amongst others

yamcs-core/src/main/java/org/yamcs/web/rest/AbstractRestRequestHandler.java
The content-length was in before the reorganization from yamcs-web.
Added this back, because curl would show a truncated response.
=> Rest: Fix issue with long responses being truncated

yamcs-api/src/main/java/org/yamcs/protobuf/Rest.java, yamcs-api/src/main/java/org/yamcs/protobuf/SchemaRest.java, yamcs-api/src/main/rest.proto, yamcs-core/src/main/java/org/yamcs/web/rest/ApiRequestHandler.java, yamcs-core/src/main/java/org/yamcs/web/rest/ManagementRequestHandler.java, yamcs-core/src/main/java/org/yamcs/web/rest/ProcessorRequestHandler.java
creates yet another empty message. Should probably refactor this part of the api a bit later on.
=> rest: processor request handler didn't respond

.travis.yml, yamcs-core/pom.xml, yamcs-core/src/test/resources/hornetq-configuration-secure.xml
In Travis build, run first the unit tests suite and then the integration test suite.
This allows to start a new JVM and load fresh configuration files for the integration tests.
=> Travis: Unit Tests / Integration Test

make-client-package.sh
When there are multiple yamcs-core/yamcs*.jar files,
make-client-package.sh takes the latest one.
But if the latest one is a -sources jar, that one will be chosen
instead of the normal compiled jar file, which will result in a
ClassDefNotFoundException when starting the software because the
.class files are not in the -sources jar.
This commit fixes the issue by excluding the sources jar.
=> make-client-package.sh: fix issue with sources jar

yamcs-core/etc/event-decoder.yaml.sample
Since event-decoder.yaml is only a non-mandatory sample configuration
file, the name should reflect this.
This is now consistent with event-viewer.yaml.sample
=> Rename event-decoder.yaml to *.sample

yamcs-api/src/main/java/org/yamcs/utils/CcsdsPacket.java, yamcs-api/src/test/java/org/yamcs/api/CcsdsPacketTest.java
The old toString() of CcsdsPacket did not output the final
ASCII bytes of a CcsdsPacket if the size was not a multiple of 16.
It also did not have any unit tests.
This commit improves the toString() by ensuring all ASCII bytes are
output and adds 2 unit tests to test the 16-byte-multiple and the
non-16-byte-multiple cases.
=> CcsdsPacket: improve toString() and add unit test

yamcs-core/src/main/java/org/yamcs/ui/archivebrowser/ArchivePanel.java, yamcs-core/src/main/java/org/yamcs/ui/yamcsmonitor/ArchiveBrowserSelector.java
The Archive Browser allows selecting TM and PP packets for a replay
but selecting PP's did not work, only TM packets were added.
This fixes B-USOC redmine issue #371
=> Fix yamcs-monitor pp replays

yamcs-core/src/main/java/org/yamcs/ui/archivebrowser/ArchivePanel.java
On the "Processed Parameters" panel of the Archive Browser,
the "Apply Selection" button is initially disabled and gets
enabled when a date range is selected.
But this behavior was broken in commit 2cbce606244 and the
button did not get enabled anymore, unless you went
to the Telemetry panel and selected a date range first.
This commit restores the button's functionality.
=> Fix disabled "Apply Selection" button for PP's

yamcs-core/etc/yamcs-ui.yaml.sample
Enable authentication in the yamcs-ui.yaml.sample
because it is often required.
It does not hurt to have authentication enabled by default
for all users because the YaMCS server will ignore any credentials
it if it's not configured for authentication anyway.
=> YaMCS client tools: enable authentication

.gitignore, yamcs-core/src/main/java/org/yamcs/ui/CliParameterExtractor.java, yamcs-core/src/main/java/org/yamcs/web/rest/ParameterReplayToChunkedCSVEncoder.java, yamcs-core/src/main/java/org/yamcs/web/rest/archive/ArchiveDownloadRestHandler.java
The changes in this pr fix a few annoyances that became apparent while talking with @tomvanbraeckel 
* parameter-extractor.sh was assuming MDB:OPS Name as the namespace. That should no longer be our default -- anywhere. With these commits it will default to XTCE qualified names (with option to override).
* parameter-extractor.sh does not correctly report server errors. This pr improves it a little bit (by removing an unnecessary stacktrace) but more improvements are needed in future work. For some reason the RestClient from yamcs-api keeps calling receiveData() even when an exception is already generated. Further the caught exception does not actually contain the RestExceptionMessage sent by the server. I suspect it may have to do with the chunked transfer logic.
* Expose options on REST …
=> Improvements to parameter extraction

yamcs-core/src/main/java/org/yamcs/xtceproc/XtceDbFactory.java
This avoids creating files with names that are too long.
Cherry-picked from master branch commit a65f9d478f0fbff6366550d1afda8eef9358139b
=> use a sha-1 checksum instead of the filename for the serialized xtcedb

yamcs-core/src/main/java/org/yamcs/web/HttpRequestHandler.java
The URL used to be http://yamcs:8090/instancename/_websocket
and it is now http://yamcs:8090/_websocket/instancename
Both are supported, but the former is deprecated.
This code was backported from master so that Yamcs Studio
builds from master are compatible with Yamcs 3.4.x
=> HttpRequestHandler: support old and new websocket path

contrib/sysvinit/yamcs-server, yamcs-api/src/main/java/org/yamcs/api/ws/WebSocketClient.java, yamcs.spec
This printed an error message on a recent centos with KDE because
of a file /etc/profile.d/kde.sh that assumes the home directory
of the yamcs user is writable (it is not).
=> Tweak init script to not use 'su - yamcs'

make-client-package.sh
The make-client-package.sh script searches for the yamcs-core*jar but should ignore the yamcs-core-javadoc and the yamcs-core-sources jar's, otherwise the client zip can end up containing the javadoc jar and not the core jar.
=> make-client-package.sh: fix issue with javadoc jar

pom.xml
The return type of some ByteBuffer methods are changed
since JDK9 causing issues when running code compiled
with JDK9+ versions on JDK8.
=> Prevent ByteBuffer compatibility issues between jdk 8 and 9+

yamcs-xtce/src/main/java/org/yamcs/xtce/xml/XtceStaxReader.java
Fix issue #352. Read byteOrder attribute in <IntegerDataEncoding> XTCE element
=> Support byte order specification in XTCE IntegerDataEncoding

yamcs-core/src/main/java/org/yamcs/tctm/ccsds/TcPacketHandler.java
This change bring the TcPacketHandler class in sync with Cop1TcPacketHandler class.
Without this change, the code throw an exception on line [102](https://github.com/yamcs/yamcs/blob/7c1634e6dab32b5553c6c5026700c2797e25eb96/yamcs-core/src/main/java/org/yamcs/tctm/ccsds/TcPacketHandler.java#L102) of TcPacketHandler.java when the cmdPostProcessor return an array larger than the binary in the PreparedCommand.  In our case, a CCSDS Encapsulated Packet header is prepended to the binary by our cmdPostProcessor, causing the mismatch.  Using the getBinaryLength() fixes the issue.
=> Use cmdPostProcessor.getBinaryLength() when fitting commands into frame

yamcs-core/src/main/java/org/yamcs/tctm/GenericPacketInputStream.java, yamcs-core/src/main/java/org/yamcs/utils/ByteArrayUtils.java
I want to use GenericPacketInputStream for the bidirectional tcp datalink but the customer's packet length field comes in LE.
=> Support for little endian in GenericPacketInputStream

docs/server-manual/services/instance/time-correlation.rst, yamcs-core/src/main/java/org/yamcs/time/TimeCorrelationService.java
Time Correlation Service has been modified to read the default time of flight set in the configuration.
Delay computation now reverts to default tof in case the ERT Start, Stop are not updated via the API instead of NaN.
An additional configuration option to enable or disable time of flight estimation is added.
=> Time Correlation Service Fixes

yamcs-core/src/main/java/org/yamcs/tctm/cfs/CfsEventDecoder.java
Hi everyone,
hope you are all doing well.
Given the fact that, when it comes to events, cfs allows you to set different sizes to the app name and event message strings, I have added options to the cfs event decoder so that we are able to set different sizes for these fields of the packet.
Thanks
Lorenzo
=> Added Options For Name Max Sizes in CfsEventDecoder

yamcs-core/src/main/java/org/yamcs/cfdp/CfdpIncomingTransfer.java, yamcs-core/src/main/java/org/yamcs/yarch/FileSystemBucket.java
Hello everyone,
hope you are all doing well.
My team and I have started to use the `cfdp` capabilities. When we set everything up we noticed that when doing a download on the downlink, YAMCS did not write the file to the filesystem. Even when configuring the buckets correctly. This is the issue I am addressing with this PR. I figured this change does not need a github discussion as it is a very trivial fix. If it does let me know.
The issue was that as you can see the implementation of getObject function in `FileSystemBucket` _assumes_ that the file exists and starts reading bytes from it. This would throw an IOException and it would not write the file to the filesystem at all. Instead I'm using  `findObject` which is specifically written for this purpose and does not start reading from …
=> Fixed bug when trying to find filesystem bucket.

yamcs-web/src/main/webapp/src/app/filetransfer/DownloadFileDialog.html, yamcs-web/src/main/webapp/src/app/filetransfer/DownloadFileDialog.ts
Previously the 'source' and 'destination' form controls were flipped for downloads, as in "source = remote entity" and "dest = local entity" to denote direction of data. But now it is "source = local entity" and "dest = remote entity" because this is where the request goes.
This is needed so we can pin the chunk size on the local entity, both for uploads and downloads.
=> File transfer chunk size

yamcs-core/src/main/java/org/yamcs/xtceproc/DataEncodingDecoder.java, yamcs-core/src/main/java/org/yamcs/xtceproc/DataEncodingEncoder.java, yamcs-core/src/main/java/org/yamcs/xtceproc/MetaCommandContainerProcessor.java, yamcs-core/src/main/java/org/yamcs/xtceproc/SequenceEntryProcessor.java, yamcs-core/src/main/java/org/yamcs/xtceproc/TcProcessingContext.java, yamcs-core/src/test/java/org/yamcs/xtce/VariableBinaryXtceTest.java, yamcs-core/src/test/java/org/yamcs/xtceproc/VariableBinaryCommandEncodingTest.java, yamcs-core/src/test/java/org/yamcs/xtceproc/VariableBinaryDecodingTest.java, yamcs-core/src/test/resources/mdb.yaml, yamcs-core/src/test/resources/xtce/VariableBinary.xml, yamcs-xtce/src/main/java/org/yamcs/xtce/BinaryDataEncoding.java, yamcs-xtce/src/main/java/org/yamcs/xtce/DataEncoding.java, yamcs-xtce/src/main/java/org/yamcs/xtce/DynamicIntegerValue.java, yamcs-xtce/src/main/java/org/yamcs/xtce/xml/XtceStaxReader.java
This is probably insufficient, as I have not addressed exporting the XTCE. However, it
seems to support adequately both packet decoding and command encoding using
binary types that reference an associated parameter or argument for the encoding
length. It would be interesting to get your feedback.
I did this today on my own time, so this should be covered by the Contributor
License Agreement which I submitted previously.
=> Support variable length binary types

yamcs-core/src/main/java/org/yamcs/tctm/ccsds/DownlinkTransferFrame.java, yamcs-core/src/main/java/org/yamcs/tctm/ccsds/VcTmPacketHandler.java
This merge request fixes two small issues with TransferFrame sequence numbers.
The first issue was that the `lastFrameSeq` variable were not updated when idle frames were dropped, causing lost frames to be detected in cases where there were in fact no lost transfer frames.
The second issue was with wrap-around of sequence numbers where there were an off-by-one error in the calculation, causing some transfer frames to be dropped as a result.
=> Fix issues with dropped transfer frames on a lossless link

yamcs-api/src/main/proto/yamcs/protobuf/processing/processing.proto, yamcs-core/src/main/java/org/yamcs/http/api/ProcessingApi.java
Modify BatchSetParameterValuesRequest.SetParameterValueRequest and
SetParameterValueRequest to have an optional generation time for the
new value. Modify processing API to use the generation time in the
request, if specified.
=> Allow specification of generation time in set parameter value requests

docs/server-manual/links/ccsds-frame-processing.rst, examples/ccsds-frames/src/main/java/org/yamcs/examples/ccsdsframes/SampleCltuGenerator.java, examples/ccsds-frames/src/main/yamcs/etc/yamcs.ccsds-frames.yaml, yamcs-core/src/main/java/org/yamcs/tctm/ccsds/AbstractTcFrameLink.java, yamcs-core/src/main/java/org/yamcs/tctm/ccsds/error/CltuGenerator.java
Add CUSTOM as an option for CLTU encoding. Allow specification of
custom CLTU generator class and arguments. Update documentation to
reflect new option. Add sample CLTU generator that just pads frames
to a byte size multiple. Add example of configuring a data link with
a custom CLTU generator.
=> Fix #631. Allow CUSTOM as CLTU encoding

yamcs-core/src/main/java/org/yamcs/tctm/FilePollingTmDataLink.java
This PR adds the EarthReceptionTime to a TM packet in the FilePollingTmDataLink class.
After applying this, the code executed nominaly:
Yamcs v5.7.7-SNAPSHOT
```
timeEncoding:
type: CUC
epoch: NONE
```
gives
```
11:10:44.017 fakesat [26] FilePollingTmDataLink [tm-file-polling] Injecting the content of yamcs-incoming/fakesat/tm/TLM-sample.dat
11:10:44.024 fakesat [26] FilePollingTmDataLink [tm-file-polling] yamcs-incoming/fakesat/tm/TLM-sample.dat finished
11:10:44.025 _global [26] EventProducer event: INFO; FILE_INGESTION; Ingested yamcs-incoming/fakesat/tm/TLM-sample.dat; pkt count: 1, time range: [2022-08-24T09:10:43.017Z, 2022-08-24T09:10:43.017Z]
```
and with
```
timeEncoding:
type: CUC
epoch: TAI
```
gives
```
11:12:08.007 fakesat [26] FilePollingTmDataLink [tm-file-polling] …
```
=> Add EarthReceptionTime in FilePollingTmDataLink class (yamcs#711)

yamcs-core/src/main/java/org/yamcs/cfdp/pdu/CfdpPacket.java, yamcs-core/src/main/java/org/yamcs/tctm/ccsds/error/Crc16Calculator.java, yamcs-core/src/main/java/org/yamcs/tctm/ccsds/error/CrcCciitCalculator.java
The current CFDP Packet class throw an UnsupportedOperationException when it receive packets with the CRC bit being set. Due to a noisy radio link, we have to set the CRC bit on CFDP frames for our satellite's downlink. But due to this unimplemented feature Yamcs is unable to process the packets.
This PR updates the CfdpPacket class to check the CRC if `.withCrc()` method returns true and throws a PduDecodingException to indicate that the CRC checksum is invalid. 
The toByteArray() and writeToBuffer() methods has been updated to add the CRC at the end of the buffer when the `.withCrc()` method returns true. 
Lastly the Crc16Calculator class updated to add an `compute` overload to work directly on a ByteBuffer instead of a byte array.
=> Update CFDP Packet class with CRC support

yamcs-core/src/main/java/org/yamcs/Spec.java, yamcs-core/src/main/java/org/yamcs/filetransfer/CsvListingParser.java
Without this Spec$Option.validate will run into a NullPointerException when validating the option if the element that the spec belongs to forgot to use `withSpec(Spec.ANY)` (which is the case for the CsvListingParser options but there may be other cases)
Here is a small patch to the cfdp example configuration that will trigger the mentioned NullPointerException
```
diff --git a/examples/cfdp-udp/src/main/yamcs/etc/yamcs.cfdp.yaml b/examples/cfdp-udp/src/main/yamcs/etc/yamcs.cfdp.yaml
index a766b048f..8b1623986 100644
--- a/examples/cfdp-udp/src/main/yamcs/etc/yamcs.cfdp.yaml
+++ b/examples/cfdp-udp/src/main/yamcs/etc/yamcs.cfdp.yaml
@@ -31,6 +31,14 @@ services:
- class: org.yamcs.cfdp.CfdpService
name: cfdp0
args:
+     fileListingParserClassName: org.yamcs.filetransfer.CsvListingParser
+ …
```
=> Use Spec.ANY as the default spec for Spec options

pom.xml
While investigating https://github.com/yamcs/yamcs/issues/787 , I noticed that the version of netty was several versions behind
=> Bump nettyVersion

yamcs-core/src/main/java/org/yamcs/tctm/FilePollingTmDataLink.java
In the `play()` function of the `FilePollingTmDataLink` class, the code call the `process()` function of the `packetPreprocessor` instance. In our case, we use the `PusPacketPreprocessor` class to process files with ECSS/PUS formatted packets. That `process()` function has 4 return statements that return a `null`.  Returning a `null` cause a `NullPointerException` to be thown; which in turn will cause the `FilePollingTmDataLink` class's processing thread to terminate and the class stops processing any more files. On our production server, we had to manually find and remove the offending file and then restart the polling link before any more processing could happen.
This PR adds a check for the `null`, thus discarding that one packet and keeps the `FilePollingTmDataLink` active in cases of …
=> Fix NullPointerException in FilePollingTmDataLink class

yamcs-core/src/main/java/org/yamcs/tctm/ccsds/AbstractTmFrameLink.java, yamcs-core/src/main/java/org/yamcs/tctm/ccsds/UdpTmFrameLink.java
I noticed that the "Valid Datagrams" and "Invalid Datagrams" in the UdpTmFrameLink are not very useful right now since AbstractTmFrameLink increments frameCount before actually trying to decode the frame (which means that even frames with a corrupted header or an invalid FECF are counted in "Valid Datagrams".
Additionally, the frameCount was not reset in resetCounters() so I added this as well.
Let me know if I should add a test case for this somewhere.
=> Count invalid frames in AbstractTmFrameLink

yamcs-api/src/main/proto/yamcs/protobuf/mdb/mdb.proto, yamcs-core/src/main/java/org/yamcs/http/api/XtceToGpbAssembler.java
Added the argument type's name from the MDb to the ArgumentTypeInfo proto. Looks like the parameter type's name does appear to be a part of the ParameterTypeInfo, but not ArgumentTypeInfo.
=> Add argument type's name to the argument info

yamcs-core/src/main/java/org/yamcs/StreamTmPacketProvider.java
If a stream is referenced in `processor.yaml`, but then not defined in `yamcs.sle.yaml`, yamcs panics.
This PR adds a simple check and throw an exception with a proper message.
=> Throw exception when TM stream is missing in configuration

yamcs-core/src/main/java/org/yamcs/cfdp/CfdpService.java, yamcs-core/src/main/java/org/yamcs/cfdp/pdu/ProxyPutRequest.java
When requesting a file from a remote entity, a ProxyPutRequest is sent. 
Previously, the destination entity ID was trimmed to the smallest entity ID buffer size that fits. 
When the destination entity ID is small (1), it only uses one byte.
This confused the CFDP server I'm working on, since it expected the size of that field to be fixed (to the default of 2 bytes). 
I'm not sure if expecting that to be fixed for a given server config is reasonable or not, so feel free to close this PR if it's working as intended, and I'll change my server.
=> Use the configured entityIdLength for ProxyPutRequest

yamcs-core/src/main/java/org/yamcs/tctm/ccsds/UslpFrameDecoder.java
Otherwise, 192 (12 << 4) gets interpreted as -4 and USLP frames are not decoded.
I'm not sure if my proposed fix is the right way to go about it. I'm still kind of confused about the fact that `byte` is a signed integer in Java.
Also let me know if you'd like a test for this.
=> Interpret USLP version number as a byte instead of int

yamcs-core/src/main/java/org/yamcs/tctm/ccsds/UslpFrameDecoder.java, yamcs-core/src/test/java/org/yamcs/tctm/ccsds/UslpFrameDecoderTest.java
Previously only TFDZ construction rule 0b000 was supported. I've added support for 0b111 (variable length TFDZ, no segmentation) because that's what we're using, but I think the same can be applied to the other construction rules.
=> Add support for variable length USLP frames

packet-viewer/src/main/java/org/yamcs/ui/packetviewer/PacketViewer.java, tests/src/test/java/org/yamcs/tests/PermissionsTest.java, yamcs-core/src/main/java/org/yamcs/http/Context.java, yamcs-core/src/main/java/org/yamcs/http/api/MdbApi.java, yamcs-core/src/main/java/org/yamcs/http/api/ParameterListsApi.java, yamcs-core/src/main/java/org/yamcs/http/api/ParameterValuesApi.java, yamcs-core/src/main/java/org/yamcs/http/api/ProcessingApi.java, yamcs-core/src/main/java/org/yamcs/http/api/StreamArchiveApi.java, yamcs-core/src/main/java/org/yamcs/parameter/ParameterWithIdRequestHelper.java, yamcs-core/src/main/java/org/yamcs/security/User.java, yamcs-xtce/src/main/java/org/yamcs/xtce/NameDescription.java
Allows to set parameter read and write permissions using the `ops://` prefix
=> Add support for using OPS names in ReadParameter and WriteParameter object permissions
