yamcs-web/src/main/java/org/yamcs/protobuf/Rest.java
yamcs-web/src/main/java/org/yamcs/protobuf/SchemaRest.java
yamcs-web/src/main/java/org/yamcs/web/rest/AbstractRestRequestHandler.java
yamcs-web/src/main/java/org/yamcs/web/rest/ApiRequestHandler.java
yamcs-web/src/main/java/org/yamcs/web/rest/ArchiveRequestHandler.java
yamcs-web/src/main/java/org/yamcs/web/rest/CommandingRequestHandler.java
yamcs-web/src/main/java/org/yamcs/web/rest/InternalServerErrorException.java
yamcs-web/src/main/java/org/yamcs/web/rest/MdbRequestHandler.java
yamcs-web/src/main/java/org/yamcs/web/rest/RestException.java
yamcs-web/src/main/rest.proto

Some changes to match code with info on wiki. Does not break compatibility with beta.3. Chunks will be next, but doing this in parallel with cs-studio where a big refactoring is ongoing.

Few tweaks to rest api

---

yamcs-core/src/main/java/org/yamcs/web/rest/ArchiveRequestHandler.java

the 'stream'-option is for a later commit. Busy on other things now

Probably fix the non-streaming side of archive request handler

---

yamcs-core/src/main/java/org/yamcs/xtceproc/MetaCommandProcessor.java
yamcs-core/src/test/java/org/yamcs/commanding/CommandingManagerTest.java

equality comparison between an Argument and a String

Fix check on re-assigning command inheritance arguments

---

yamcs-core/src/main/java/org/yamcs/YamcsServer.java

Solves the service start timeout issue.

Restored "yamcsstartup success" message.

---

yamcs-core/src/main/java/org/yamcs/web/rest/MdbRequestHandler.java

Before it would send all aliases, and there was no way of retrieving the qualified names.

Rest: mdb/parameters now sends qualified names by default

---

yamcs-api/src/main/java/org/yamcs/api/ws/WebSocketClientCallbackListener.java
yamcs-api/src/main/java/org/yamcs/api/ws/WebSocketClientHandler.java
yamcs-api/src/main/java/org/yamcs/protobuf/SchemaWebsocket.java
yamcs-api/src/main/java/org/yamcs/protobuf/SchemaYamcs.java
yamcs-api/src/main/java/org/yamcs/protobuf/Websocket.java
yamcs-api/src/main/java/org/yamcs/protobuf/Yamcs.java
yamcs-api/src/main/websocket.proto
yamcs-api/src/main/yamcs.proto
yamcs-api/src/test/python/publish-stream.py
yamcs-api/src/test/python/subscribe-stream.py
yamcs-core/src/main/java/org/yamcs/archive/EventRecorder.java
yamcs-core/src/main/java/org/yamcs/web/HttpSocketServer.java
yamcs-core/src/main/java/org/yamcs/web/websocket/CommandHistoryResource.java
yamcs-core/src/main/java/org/yamcs/web/websocket/ProtobufDecoder.java
yamcs-core/src/main/java/org/yamcs/web/websocket/StreamResource.java
yamcs-core/src/main/java/org/yamcs/web/websocket/WebSocketDecodeContext.java
yamcs-core/src/main/java/org/yamcs/web/websocket/WebSocketProcessorClient.java
yamcs-core/src/test/java/org/yamcs/AbstractIntegrationTest.java

No protobuf support yet. Didn't really know a use case.
As such, it also uses Yamcs.Value.
Up for discussion

First go at streams over web socket

---

yamcs-core/src/main/java/org/yamcs/AlarmReporter.java

This reverts commit 5071320ea46c9ea3c08dd849b89b636702eeaadd.

Revert "Fix probable typo in AlarmReporter"

---

yamcs-api/src/main/java/org/yamcs/api/ws/WebSocketClient.java

The reconnection was commented out, I put it back with an overload of connect for facility.

Enable reconnection in WebSocketClient

---

yamcs-api/src/main/java/org/yamcs/protobuf/Rest.java
yamcs-api/src/main/java/org/yamcs/protobuf/SchemaRest.java
yamcs-api/src/main/rest.proto
yamcs-core/src/main/java/org/yamcs/web/rest/RestHandler.java
yamcs-core/src/main/java/org/yamcs/web/rest/archive/ArchiveDownloadRestHandler.java
yamcs-core/src/main/java/org/yamcs/web/rest/archive/ArchiveParameter2RestHandler.java
yamcs-core/src/main/java/org/yamcs/web/rest/archive/ArchiveParameterRestHandler.java

Add support for dumping all parameters without specifying which

---

make-client-package.sh

Add error handling and improved output

make-client-package.sh: make minor improvements

---

yamcs-core/src/main/java/org/yamcs/tctm/CcsdsSeqAndChecksumFiller.java
yamcs-core/src/main/java/org/yamcs/tctm/TcpTcDataLink.java
yamcs-simulation/src/main/java/org/yamcs/simulator/CCSDSPacket.java
yamcs-simulation/src/main/java/org/yamcs/simulator/launchland/LaunchAndLandingSimulator.java

Fix so too small packets are no longer sent to the simulator

size check fix

---

yamcs-api/src/main/yamcs.proto
yamcs-core/src/main/java/org/yamcs/archive/CommandHistoryReplayHandler.java
yamcs-core/src/main/java/org/yamcs/archive/EventReplayHandler.java
yamcs-core/src/main/java/org/yamcs/archive/ParameterReplayHandler.java
yamcs-core/src/main/java/org/yamcs/archive/ReplayHandler.java
yamcs-core/src/main/java/org/yamcs/archive/ReplayServer.java
yamcs-core/src/main/java/org/yamcs/archive/XtceTmReplayHandler.java
yamcs-core/src/main/java/org/yamcs/archive/YarchReplay.java

Also includes a bunch of formatting stuff with the new rules enabled.

Replay everything upon empty replay request

---

yamcs-core/etc/event-viewer.yaml.sample
yamcs-core/src/main/java/org/yamcs/tctm/TcpTmDataLink.java
yamcs-core/src/main/java/org/yamcs/ui/eventviewer/EventTable.java
yamcs-core/src/main/java/org/yamcs/ui/eventviewer/EventTableModel.java
yamcs-core/src/main/java/org/yamcs/ui/eventviewer/EventViewer.java
yamcs-core/src/main/java/org/yamcs/ui/eventviewer/PreferencesDialog.java
yamcs-core/src/main/java/org/yamcs/ui/eventviewer/YamcsEventReceiver.java

Checkbox to choose columns to save;
Read link status parameter from config file

Eraeventviewer

---

yamcs-api/src/main/java/org/yamcs/api/YamcsConnectionProperties.java
yamcs-api/src/main/java/org/yamcs/api/ws/WebSocketClient.java
yamcs-api/src/main/java/org/yamcs/api/ws/WebSocketClientHandler.java

This makes it possible to connect a Yamcs v4 client
with an old Yamcs instance.

Add wsclient option to try legacy url on handshake 404

---

yamcs-api/src/main/java/org/yamcs/protobuf/Rest.java
yamcs-api/src/main/java/org/yamcs/protobuf/YamcsManagement.java
yamcs-api/src/main/yamcsManagement.proto

Allow v3 'systemPrivileges' to still pass to v4 client

---

yamcs-web/packages/app/src/app/mdb/parameters/ParameterChartTab.html
yamcs-web/packages/app/src/app/mdb/parameters/ParameterChartTab.ts

Hi
In most cases the 15 minutes interval is more suitable.

additional durations range

---

yamcs-core/src/main/java/org/yamcs/xtce/SpaceSystemLoader.java
yamcs-core/src/main/java/org/yamcs/xtce/SpreadsheetLoader.java
yamcs-core/src/main/java/org/yamcs/xtce/XtceLoader.java
yamcs-core/src/main/java/org/yamcs/xtceproc/XtceDbFactory.java

Allow command options to refer to commands loaded on previously loaded spacesystem.

Spreadsheet MDB - Command options

---

distribution/pom.xml
packet-viewer/pom.xml
pom.xml
simulation/pom.xml
yamcs-api/pom.xml
yamcs-artemis/pom.xml
yamcs-client/pom.xml
yamcs-core/pom.xml
yamcs-tse/pom.xml
yamcs-web/pom.xml
yamcs-xtce/pom.xml

Prepare release yamcs-4.10.9.2

---

yamcs-core/src/main/java/org/yamcs/security/Directory.java
yamcs-core/src/main/java/org/yamcs/security/Role.java
yamcs-core/src/main/java/org/yamcs/security/YamlAuthModule.java

security YamlAuthModule, add default role attribute

---

yamcs-api/src/main/proto/yamcs/protobuf/filetransfer/filetransfer.proto
yamcs-core/src/main/java/org/yamcs/cfdp/CfdpIncomingTransfer.java
yamcs-core/src/main/java/org/yamcs/cfdp/CfdpOutgoingTransfer.java
yamcs-web/src/main/webapp/src/app/client/types/filetransfer.ts
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferPage.ts
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferTable.html
yamcs-web/src/main/webapp/src/app/filetransfer/OngoingTransfersTab.ts

Couldn't get the rebase to work so I deleted the fork and created a new one, then copied the changes manually. This pull request should now contain only one commit and no more older commits.

Added TransferState.CANCELLING

---

yamcs-core/src/main/java/org/yamcs/cfdp/EntityConf.java
yamcs-core/src/main/java/org/yamcs/http/api/FileTransferApi.java
yamcs-web/src/main/webapp/src/app/client/types/filetransfer.ts
yamcs-web/src/main/webapp/src/app/filetransfer/DownloadFileDialog.html
yamcs-web/src/main/webapp/src/app/filetransfer/DownloadFileDialog.ts
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferModule.ts
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferPage.html
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferPage.ts
yamcs-web/src/main/webapp/src/app/filetransfer/UploadFileDialog.html

I also changed a bit the wording on the Upload/Download dialogs.
FileTransferCapabilities are now taken into account.

Added download dialog to web interface, small fixes

---

yamcs-core/src/main/java/org/yamcs/tctm/FixedPacketInputStream.java
yamcs-core/src/main/java/org/yamcs/tctm/TcpTcTmDataLink.java
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferTable.html
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferTable.ts

New class TcpTcTmDataLink which is a combination of TcpTcDataLink and TcpTmDataLink.
New class FixedPacketInputStream which simply reads packets of fixed size which can be configured.
Small change to the percent display of file transfers.

New DataLink, new PacketInputStream, finetuning for FileTransfer upload dialog

---

docs/server-manual/services/instance/cfs-event-decoder.rst

Hello everyone,
Figured I'd update the documentation given that we added these event options.
Thanks in advance
Lorenzo

Cfs events docs

---

yamcs-core/src/main/java/org/yamcs/cfdp/PutRequest.java
yamcs-web/src/main/webapp/src/app/filetransfer/FileTransferPage.ts
yamcs-web/src/main/webapp/src/app/filetransfer/OngoingTransfersTab.ts

this time without lock file...

Fixed ONGOING transfer list in file transfers UI

---

yamcs-core/src/main/java/org/yamcs/cfdp/CfdpIncomingTransfer.java

Fix warning message for failed transfers

---

docs/server-manual/links/ccsds-frame-processing.rst

-Typo on docs

---

docs/server-manual/links/ccsds-frame-processing.rst

Update link to CCSDS 131.0

---

yamcs-core/src/main/java/org/yamcs/cfdp/CfdpService.java
yamcs-core/src/main/java/org/yamcs/http/api/FileTransferApi.java

Correctly unsubscribing from inStream when stopping a CfdpService

Fix CFDP service stop

---

yamcs-core/src/main/java/org/yamcs/http/api/LinksApi.java
yamcs-core/src/main/java/org/yamcs/management/LinkManager.java
yamcs-core/src/main/java/org/yamcs/tctm/TcDataLink.java

(associated PR: https://github.com/yamcs/yamcs-sle/pull/12)

Tweak command sending checks for yamcs/yamcs-sle

---

docs/server-manual/services/instance/cfdp.rst
examples/cfdp/src/main/yamcs/etc/yamcs.cfdp.yaml
yamcs-api/src/main/proto/yamcs/protobuf/filetransfer/filetransfer.proto
yamcs-core/src/main/java/org/yamcs/cfdp/CfdpOutgoingTransfer.java
yamcs-core/src/main/java/org/yamcs/cfdp/CfdpService.java
yamcs-core/src/main/java/org/yamcs/cfdp/QueuedCfdpOutgoingTransfer.java
yamcs-core/src/main/java/org/yamcs/filetransfer/FileListingService.java
yamcs-core/src/main/java/org/yamcs/filetransfer/TransferOptions.java
yamcs-core/src/main/java/org/yamcs/http/HttpTranscoder.java
yamcs-core/src/main/java/org/yamcs/http/api/FileTransferApi.java
yamcs-core/src/test/java/org/yamcs/cfdp/CfdpDownlinkIntegrationTest.java
yamcs-web/src/main/webapp/src/app/admin/shared/AdminPage.ts
yamcs-web/src/main/webapp/src/app/appbase/pages/AppComponent.ts
yamcs-web/src/main/webapp/src/app/client/YamcsClient.ts
yamcs-web/src/main/webapp/src/app/client/types/filetransfer.ts
yamcs-web/src/main/webapp/src/app/core/services/PreferenceStore.ts
yamcs-web/src/main/webapp/src/app/filetransfer/TransferFileDialog.css
yamcs-web/src/main/webapp/src/app/filetransfer/TransferFileDialog.html
yamcs-web/src/main/webapp/src/app/filetransfer/TransferFileDialog.ts
yamcs-web/src/main/webapp/src/app/shared/progress/Progress.css
yamcs-web/src/main/webapp/src/app/shared/progress/Progress.html
yamcs-web/src/main/webapp/src/app/shared/progress/Progress.ts
yamcs-web/src/main/webapp/src/app/shared/template/InstancePage.ts
yamcs-web/src/main/webapp/src/app/storage/StoragePage.ts
yamcs-web/src/main/webapp/src/styles/form.css

- Simplify filetransfer option protobuf
- Add CFDP PDU size and delay file transfer options & configuration
- Add recalling of selected values in TransferFileDialog

Various file transfer options improvements

---

yamcs-core/src/main/java/org/yamcs/tctm/ccsds/Cop1TcPacketHandler.java

Add enumerated data type for cop1Status.state

---

.github/workflows/main.yml
.github/workflows/quality.yml
yamcs-core/src/main/java/org/yamcs/algorithms/ScriptAlgorithmExecutor.java
yamcs-core/src/main/java/org/yamcs/http/api/PacketsApi.java
yamcs-web/src/main/java/org/yamcs/web/WebFileDeployer.java
yamcs-web/src/main/webapp/projects/webapp/src/app/appbase/pages/AppComponent.css
yamcs-web/src/main/webapp/projects/webapp/src/app/appbase/pages/AppComponent.html
yamcs-web/src/main/webapp/projects/webapp/src/app/events/EventsPage.css
yamcs-web/src/main/webapp/projects/webapp/src/app/events/EventsPage.html
yamcs-web/src/main/webapp/projects/webapp/src/app/mdb/commands/CommandDetail.html
yamcs-web/src/main/webapp/projects/webapp/src/app/mdb/containers/ContainerDetail.html

Misc minor

---

yamcs-core/src/test/java/org/yamcs/mdb/XtceStringDecodingTest.java
yamcs-core/src/test/resources/xtce/strings-tm.xml
yamcs-xtce/src/main/java/org/yamcs/xtce/xml/XtceStaxReader.java

This merge request adds a test case for issue #844 as well as the proposed fix.

String data encoding dynamic value

---

yamcs-core/src/main/java/org/yamcs/tctm/pus/PusPacketPreprocessor.java

Fixed two minor issues in the code.

Remove unused import statements and fix spelling error in log message

---

yamcs-core/src/main/java/org/yamcs/tctm/AbstractTcTmParamLink.java

Commit 61ed6adeaa changed the initialization scheme for CommandPostProcessors but only applied this to AbstractTcDataLink. AbstractTcTmParamLink did not get the same treatment which means that all links that used it (e.g. TcpTcTmDataLink) were broken with standard yamcs command postprocessor.

Apply the CommandPreprocessor init scheme from 61ed6adeaa to AbstractTcTmParamLink
